### ISSUE TITLE
sqlite3 : create function regexp with python

### ISSUE THREAD

**Issue by marianoju** [EvgeniyMakhmudov/sberbank_fake_gate#5]
Hej @EvgeniyMakhmudov!

I am sorry to bother you with this one via GitHub, but I found [your answer to this question on stackoverflow](https://stackoverflow.com/a/50066799/3364859) and tried to reproduce it, but it doesn't print any output, see [my notebook](https://github.com/marianoju/neuefische/blob/colors/projects/colors/REGEXP_function.ipynb). Would you mind checking? 

Best regards!

**Comment by EvgeniyMakhmudov** [comment]
@marianoju hello. I check and found that my edit of original post is not correct, because arguments are not in right order. I edit again post in SO and now it is correct. You can reproduce it and found expected output.

**Comment by marianoju** [comment]
:+1: Works fine now! Thanks!
